spring:
  application:
    name: orchestrator
  datasource:
    url: jdbc:postgresql://localhost:5432/orchestrator
    username: orchestrator
    password: orchestrator
  sql:
    init:

      mode: never
  session:
    jdbc:
      initialize-schema: always

server:
  port: 8080